# Generated by Django 4.0.4 on 2022-05-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'verbose_name': 'CostCenter',
                'verbose_name_plural': 'CostCenters',
                'db_table': 'cost_center',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('account', models.IntegerField()),
                ('account_sub', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('code_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'db_table': 'warehouse',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='code_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.provider'),
        ),
        migrations.CreateModel(
            name='DeliverySC208',
            fields=[
                ('voucher', models.AutoField(editable=False, primary_key=True, serialize=False, unique_for_year='date_stamp')),
                ('request_voucher_1', models.IntegerField()),
                ('request_voucher_2', models.IntegerField()),
                ('request_plan', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('existence', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ci_cost_center_receiver', models.IntegerField()),
                ('ci_warehouse_dispatcher', models.IntegerField()),
                ('date_stamp', models.DateField(auto_now=True)),
                ('code_cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.costcenter')),
                ('code_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('number_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.warehouse')),
            ],
            options={
                'verbose_name': 'DeliverySC208',
                'verbose_name_plural': 'DeliverySC208s',
                'db_table': 'delivery_sc_2_08',
            },
        ),
        migrations.AddField(
            model_name='costcenter',
            name='code_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='code_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unit'),
        ),
    ]
