# Generated by Django 3.1.4 on 2020-12-18 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('measure_unit', models.CharField(choices=[('U', 'unidad'), ('Kg', 'kilogramo'), ('Lb', 'libra'), ('Oz', 'onza'), ('m', 'metro'), ('cm', 'centimetro'), ('mm', 'milimetro'), ('L', 'litro'), ('mL', 'mililitro')], default='U', max_length=5)),
                ('price_per_unit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_stream.product')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_stream.product')),
            ],
        ),
    ]
