# Generated by Django 3.1.4 on 2020-12-19 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_voucher',
            fields=[
                ('voucher_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('date_stamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reception_voucher',
            fields=[
                ('voucher_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('date_stamp', models.DateField()),
                ('bill', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Return_voucher',
            fields=[
                ('voucher_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('date_stamp', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='voucher_kind',
            field=models.CharField(choices=[('D', 'delivery'), ('R', 'return')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('delivery_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_stream.delivery_voucher')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_stream.product')),
                ('reception_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_stream.reception_voucher')),
                ('return_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_stream.return_voucher')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='voucher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_stream.return_voucher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='voucher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_stream.reception_voucher'),
            preserve_default=False,
        ),
    ]
